apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: summer0531/multi-react
      ports:
        - containerPort: 3000